const colors = {
  light: {
    text: "#0F172A",
    tint: "#3B82F6",
    background: "#F0F4FF",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1E40AF",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1E3A8A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DBEAFE",
    input: "#DBEAFE",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
