export const CAMPUSES = [
  { id: "c1", name: "IIT Delhi", city: "Delhi", area: "Hauz Khas" },
  { id: "c2", name: "DTU Delhi", city: "Delhi", area: "Rohini" },
  { id: "c3", name: "BITS Pilani", city: "Pilani", area: "Pilani" },
  { id: "c4", name: "IIT Bombay", city: "Mumbai", area: "Powai" },
  { id: "c5", name: "VIT Vellore", city: "Vellore", area: "Katpadi" },
  { id: "c6", name: "Manipal University", city: "Manipal", area: "Udupi" },
  { id: "c7", name: "NIT Trichy", city: "Tiruchirappalli", area: "Tanjore Road" },
  { id: "c8", name: "NSIT Delhi", city: "Delhi", area: "Dwarka" },
];

export const RESTAURANTS = [
  {
    id: "r1",
    name: "Green Bowl",
    tagline: "Fresh North Indian home meals",
    cuisine: "North Indian",
    rating: 4.4,
    reviewCount: 128,
    distance: "800m",
    deliveryTime: "20-30 min",
    isVeg: true,
    description:
      "Freshly prepared North Indian home-style meals with seasonal vegetables and homemade dal. No artificial colors or preservatives.",
    address: "Near Gate 2, Campus Area",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m1", "m2", "m3"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    maxCapacity: 60,
    accentColor: "#22C55E",
  },
  {
    id: "r2",
    name: "Spice Garden",
    tagline: "Authentic South Indian flavors",
    cuisine: "South Indian",
    rating: 4.2,
    reviewCount: 95,
    distance: "1.2km",
    deliveryTime: "25-35 min",
    isVeg: true,
    description:
      "Authentic South Indian tiffin and meals. Our idli-sambar and masala dosa are student favourites across campus.",
    address: "Old Market Road, Campus Area",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m4", "m5"],
    lunchAvailable: true,
    dinnerAvailable: false,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    maxCapacity: 45,
    accentColor: "#F97316",
  },
  {
    id: "r3",
    name: "Annapurna Tiffin",
    tagline: "Homely meals like mom makes",
    cuisine: "Home-style",
    rating: 4.6,
    reviewCount: 201,
    distance: "600m",
    deliveryTime: "15-25 min",
    isVeg: false,
    description:
      "Daily-changing home-style thali with fresh seasonal ingredients. Both veg and non-veg options available every day.",
    address: "Behind Boys Hostel A, Campus",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m6", "m7", "m8"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    maxCapacity: 80,
    accentColor: "#8B5CF6",
  },
  {
    id: "r4",
    name: "Protein Hub",
    tagline: "High-protein meals for active students",
    cuisine: "High Protein",
    rating: 4.3,
    reviewCount: 77,
    distance: "1.5km",
    deliveryTime: "30-40 min",
    isVeg: false,
    description:
      "Specially crafted high-protein meals for gym-goers and athletes. Macro-tracked and nutritionist-approved recipes.",
    address: "Sports Complex Lane, Campus",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m9", "m10"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    maxCapacity: 40,
    accentColor: "#EF4444",
  },
  {
    id: "r5",
    name: "Fresh Bites",
    tagline: "Light, fresh, and delicious",
    cuisine: "Multi-cuisine",
    rating: 4.1,
    reviewCount: 63,
    distance: "2km",
    deliveryTime: "30-40 min",
    isVeg: true,
    description:
      "Healthy, light meals with a variety of cuisines. Great for students who want something different each day.",
    address: "New Market, Campus Boundary",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m11", "m12"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    maxCapacity: 35,
    accentColor: "#06B6D4",
  },
];

export const MEALS = [
  {
    id: "m1",
    restaurantId: "r1",
    restaurantName: "Green Bowl",
    name: "Mini Thali",
    description:
      "Dal, sabzi, rice, 2 roti, pickle and curd. A complete balanced meal freshly prepared daily.",
    type: "both" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 650,
    protein: "22g",
    spice: "medium" as const,
    image: "thali" as const,
  },
  {
    id: "m2",
    restaurantId: "r1",
    restaurantName: "Green Bowl",
    name: "Rajma Rice",
    description:
      "Creamy rajma with basmati rice, pickle and salad. North Indian comfort food at its best.",
    type: "both" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 580,
    protein: "18g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m3",
    restaurantId: "r1",
    restaurantName: "Green Bowl",
    name: "Paneer Thali",
    description:
      "Rich paneer butter masala, rice, 3 roti, dal, raita and pickle. A premium veg option.",
    type: "both" as const,
    vegType: "veg" as const,
    passEligible: false,
    premiumExtra: 40,
    calories: 720,
    protein: "28g",
    spice: "medium" as const,
    image: null,
  },
  {
    id: "m4",
    restaurantId: "r2",
    restaurantName: "Spice Garden",
    name: "Masala Dosa",
    description:
      "Crispy dosa with spiced potato filling, sambar and two chutneys. A South Indian classic.",
    type: "lunch" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 520,
    protein: "12g",
    spice: "medium" as const,
    image: "dosa" as const,
  },
  {
    id: "m5",
    restaurantId: "r2",
    restaurantName: "Spice Garden",
    name: "Idli Sambar",
    description:
      "3 soft idlis with fresh sambar and coconut chutney. Light, filling, and nutritious.",
    type: "lunch" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 380,
    protein: "10g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m6",
    restaurantId: "r3",
    restaurantName: "Annapurna Tiffin",
    name: "Veg Tiffin",
    description:
      "Dal tadka, seasonal sabzi, rice, 2 phulka, pickle and chutney. Home taste, delivered.",
    type: "both" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 600,
    protein: "20g",
    spice: "mild" as const,
    image: "tiffin" as const,
  },
  {
    id: "m7",
    restaurantId: "r3",
    restaurantName: "Annapurna Tiffin",
    name: "Egg Tiffin",
    description:
      "Egg curry or bhurji, rice, 2 phulka, dal and salad. High protein, home-style.",
    type: "both" as const,
    vegType: "egg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 650,
    protein: "30g",
    spice: "medium" as const,
    image: null,
  },
  {
    id: "m8",
    restaurantId: "r3",
    restaurantName: "Annapurna Tiffin",
    name: "Chicken Thali",
    description:
      "Chicken curry, rice, 2 roti, dal, raita and pickle. Premium non-veg meal.",
    type: "both" as const,
    vegType: "non-veg" as const,
    passEligible: false,
    premiumExtra: 60,
    calories: 750,
    protein: "42g",
    spice: "hot" as const,
    image: null,
  },
  {
    id: "m9",
    restaurantId: "r4",
    restaurantName: "Protein Hub",
    name: "Grilled Chicken Bowl",
    description:
      "150g grilled chicken, brown rice, steamed vegetables and protein dressing. Macro-tracked.",
    type: "both" as const,
    vegType: "non-veg" as const,
    passEligible: false,
    premiumExtra: 80,
    calories: 480,
    protein: "48g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m10",
    restaurantId: "r4",
    restaurantName: "Protein Hub",
    name: "Paneer Power Bowl",
    description:
      "100g paneer, quinoa, roasted vegetables and high-protein dal. Vegetarian gains.",
    type: "both" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 520,
    protein: "35g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m11",
    restaurantId: "r5",
    restaurantName: "Fresh Bites",
    name: "Garden Fresh Thali",
    description:
      "Seasonal salad, soup, paneer dish, rice and 2 roti. Light and wholesome.",
    type: "lunch" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 550,
    protein: "18g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m12",
    restaurantId: "r5",
    restaurantName: "Fresh Bites",
    name: "Asian Noodle Bowl",
    description:
      "Sautéed vegetables, noodles in a light soy-ginger broth. A campus favourite.",
    type: "lunch" as const,
    vegType: "veg" as const,
    passEligible: true,
    premiumExtra: 0,
    calories: 490,
    protein: "14g",
    spice: "medium" as const,
    image: null,
  },
];

export const PASS_PLANS = [
  {
    id: "starter",
    name: "Starter Pass",
    meals: 5,
    price: 999,
    validDays: 10,
    perMeal: 199.8,
    popular: false,
    description: "Try it out for a week",
  },
  {
    id: "weekly",
    name: "Weekly Pass",
    meals: 10,
    price: 1899,
    validDays: 15,
    perMeal: 189.9,
    popular: false,
    description: "A couple weeks of meals",
  },
  {
    id: "monthly",
    name: "Monthly Pass",
    meals: 30,
    price: 5699,
    validDays: 45,
    perMeal: 189.9,
    popular: true,
    description: "Best value for regular students",
  },
  {
    id: "heavy",
    name: "Heavy Pass",
    meals: 60,
    price: 10999,
    validDays: 75,
    perMeal: 183.3,
    popular: false,
    description: "Two meals daily, all semester",
  },
];
