export const CAMPUSES = [
  { id: "c1", name: "IIT Delhi", city: "Delhi", area: "Hauz Khas" },
  { id: "c2", name: "DTU Delhi", city: "Delhi", area: "Rohini" },
  { id: "c3", name: "BITS Pilani", city: "Pilani", area: "Pilani" },
  { id: "c4", name: "IIT Bombay", city: "Mumbai", area: "Powai" },
  { id: "c5", name: "VIT Vellore", city: "Vellore", area: "Katpadi" },
  { id: "c6", name: "Manipal University", city: "Manipal", area: "Udupi" },
  { id: "c7", name: "NIT Trichy", city: "Tiruchirappalli", area: "Tanjore Road" },
  { id: "c8", name: "NSIT Delhi", city: "Delhi", area: "Dwarka" },
];

export const RESTAURANTS = [
  {
    id: "r1",
    name: "Green Bowl",
    tagline: "Fresh North Indian home meals",
    cuisine: "North Indian",
    rating: 4.4,
    reviewCount: 128,
    distance: "800m",
    deliveryTime: "20-30 min",
    isVeg: true,
    description:
      "Freshly prepared North Indian home-style meals with seasonal vegetables and homemade dal. No artificial colors or preservatives.",
    address: "Near Gate 2, Campus Area",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m1", "m2", "m3"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    maxCapacity: 60,
    accentColor: "#22C55E",
    lunchStartPrice: 179,
    dinnerStartPrice: 208,
  },
  {
    id: "r2",
    name: "Spice Garden",
    tagline: "Authentic South Indian flavors",
    cuisine: "South Indian",
    rating: 4.2,
    reviewCount: 95,
    distance: "1.2km",
    deliveryTime: "25-35 min",
    isVeg: true,
    description:
      "Authentic South Indian tiffin and meals. Our idli-sambar and masala dosa are student favourites across campus.",
    address: "Old Market Road, Campus Area",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m4", "m5"],
    lunchAvailable: true,
    dinnerAvailable: false,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    maxCapacity: 45,
    accentColor: "#F97316",
    lunchStartPrice: 161,
    dinnerStartPrice: 0,
  },
  {
    id: "r3",
    name: "Annapurna Tiffin",
    tagline: "Homely meals like mom makes",
    cuisine: "Home-style",
    rating: 4.6,
    reviewCount: 201,
    distance: "600m",
    deliveryTime: "15-25 min",
    isVeg: false,
    description:
      "Daily-changing home-style thali with fresh seasonal ingredients. Both veg and non-veg options available every day.",
    address: "Behind Boys Hostel A, Campus",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m6", "m7", "m8"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    maxCapacity: 80,
    accentColor: "#8B5CF6",
    lunchStartPrice: 179,
    dinnerStartPrice: 206,
  },
  {
    id: "r4",
    name: "Protein Hub",
    tagline: "High-protein meals for active students",
    cuisine: "High Protein",
    rating: 4.3,
    reviewCount: 77,
    distance: "1.5km",
    deliveryTime: "30-40 min",
    isVeg: false,
    description:
      "Specially crafted high-protein meals for gym-goers and athletes. Macro-tracked and nutritionist-approved recipes.",
    address: "Sports Complex Lane, Campus",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m9", "m10"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    maxCapacity: 40,
    accentColor: "#EF4444",
    lunchStartPrice: 206,
    dinnerStartPrice: 224,
  },
  {
    id: "r5",
    name: "Fresh Bites",
    tagline: "Light, fresh, and delicious",
    cuisine: "Multi-cuisine",
    rating: 4.1,
    reviewCount: 63,
    distance: "2km",
    deliveryTime: "30-40 min",
    isVeg: true,
    description:
      "Healthy, light meals with a variety of cuisines. Great for students who want something different each day.",
    address: "New Market, Campus Boundary",
    cancelCutoff: "10 PM previous day",
    mealIds: ["m11", "m12"],
    lunchAvailable: true,
    dinnerAvailable: true,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    maxCapacity: 35,
    accentColor: "#06B6D4",
    lunchStartPrice: 152,
    dinnerStartPrice: 179,
  },
];

export const MEALS = [
  {
    id: "m1",
    restaurantId: "r1",
    restaurantName: "Green Bowl",
    name: "Mini Thali",
    description:
      "Dal, sabzi, rice, 2 roti, pickle and curd. A complete balanced meal freshly prepared daily.",
    type: "both" as const,
    vegType: "veg" as const,
    calories: 650,
    protein: "22g",
    carbs: "95g",
    fat: "15g",
    fiber: "8g",
    spice: "medium" as const,
    image: "thali" as const,
  },
  {
    id: "m2",
    restaurantId: "r1",
    restaurantName: "Green Bowl",
    name: "Rajma Rice",
    description:
      "Creamy rajma with basmati rice, pickle and salad. North Indian comfort food at its best.",
    type: "both" as const,
    vegType: "veg" as const,
    calories: 580,
    protein: "18g",
    carbs: "90g",
    fat: "12g",
    fiber: "10g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m3",
    restaurantId: "r1",
    restaurantName: "Green Bowl",
    name: "Paneer Thali",
    description:
      "Rich paneer butter masala, rice, 3 roti, dal, raita and pickle. A premium veg option.",
    type: "both" as const,
    vegType: "veg" as const,
    calories: 720,
    protein: "28g",
    carbs: "80g",
    fat: "28g",
    fiber: "6g",
    spice: "medium" as const,
    image: null,
  },
  {
    id: "m4",
    restaurantId: "r2",
    restaurantName: "Spice Garden",
    name: "Masala Dosa",
    description:
      "Crispy dosa with spiced potato filling, sambar and two chutneys. A South Indian classic.",
    type: "lunch" as const,
    vegType: "veg" as const,
    calories: 520,
    protein: "12g",
    carbs: "80g",
    fat: "18g",
    fiber: "5g",
    spice: "medium" as const,
    image: "dosa" as const,
  },
  {
    id: "m5",
    restaurantId: "r2",
    restaurantName: "Spice Garden",
    name: "Idli Sambar",
    description:
      "3 soft idlis with fresh sambar and coconut chutney. Light, filling, and nutritious.",
    type: "lunch" as const,
    vegType: "veg" as const,
    calories: 380,
    protein: "10g",
    carbs: "68g",
    fat: "6g",
    fiber: "7g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m6",
    restaurantId: "r3",
    restaurantName: "Annapurna Tiffin",
    name: "Veg Tiffin",
    description:
      "Dal tadka, seasonal sabzi, rice, 2 phulka, pickle and chutney. Home taste, delivered.",
    type: "both" as const,
    vegType: "veg" as const,
    calories: 600,
    protein: "20g",
    carbs: "88g",
    fat: "14g",
    fiber: "9g",
    spice: "mild" as const,
    image: "tiffin" as const,
  },
  {
    id: "m7",
    restaurantId: "r3",
    restaurantName: "Annapurna Tiffin",
    name: "Egg Tiffin",
    description:
      "Egg curry or bhurji, rice, 2 phulka, dal and salad. High protein, home-style.",
    type: "both" as const,
    vegType: "egg" as const,
    calories: 650,
    protein: "30g",
    carbs: "72g",
    fat: "22g",
    fiber: "5g",
    spice: "medium" as const,
    image: null,
  },
  {
    id: "m8",
    restaurantId: "r3",
    restaurantName: "Annapurna Tiffin",
    name: "Chicken Thali",
    description:
      "Chicken curry, rice, 2 roti, dal, raita and pickle. Premium non-veg meal.",
    type: "both" as const,
    vegType: "non-veg" as const,
    calories: 750,
    protein: "42g",
    carbs: "70g",
    fat: "28g",
    fiber: "4g",
    spice: "hot" as const,
    image: null,
  },
  {
    id: "m9",
    restaurantId: "r4",
    restaurantName: "Protein Hub",
    name: "Grilled Chicken Bowl",
    description:
      "150g grilled chicken, brown rice, steamed vegetables and protein dressing. Macro-tracked.",
    type: "both" as const,
    vegType: "non-veg" as const,
    calories: 480,
    protein: "48g",
    carbs: "42g",
    fat: "12g",
    fiber: "6g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m10",
    restaurantId: "r4",
    restaurantName: "Protein Hub",
    name: "Paneer Power Bowl",
    description:
      "100g paneer, quinoa, roasted vegetables and high-protein dal. Vegetarian gains.",
    type: "both" as const,
    vegType: "veg" as const,
    calories: 520,
    protein: "35g",
    carbs: "48g",
    fat: "18g",
    fiber: "8g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m11",
    restaurantId: "r5",
    restaurantName: "Fresh Bites",
    name: "Garden Fresh Thali",
    description:
      "Seasonal salad, soup, paneer dish, rice and 2 roti. Light and wholesome.",
    type: "lunch" as const,
    vegType: "veg" as const,
    calories: 550,
    protein: "18g",
    carbs: "78g",
    fat: "16g",
    fiber: "12g",
    spice: "mild" as const,
    image: null,
  },
  {
    id: "m12",
    restaurantId: "r5",
    restaurantName: "Fresh Bites",
    name: "Asian Noodle Bowl",
    description:
      "Sautéed vegetables, noodles in a light soy-ginger broth. A campus favourite.",
    type: "lunch" as const,
    vegType: "veg" as const,
    calories: 490,
    protein: "14g",
    carbs: "72g",
    fat: "14g",
    fiber: "6g",
    spice: "medium" as const,
    image: null,
  },
];

export interface SubscriptionPackage {
  slot: "lunch" | "dinner" | "both";
  days: 10 | 20 | 30;
  pricePerDay: number;
  totalPrice: number;
  popular?: boolean;
  discountPct?: number;
  comboSaving?: number;
}

export const SUBSCRIPTION_PACKAGES: Record<string, SubscriptionPackage[]> = {
  r1: [
    { slot: "lunch", days: 10, pricePerDay: 189, totalPrice: 1890 },
    { slot: "lunch", days: 20, pricePerDay: 179, totalPrice: 3580, popular: true, discountPct: 5 },
    { slot: "lunch", days: 30, pricePerDay: 170, totalPrice: 5100, discountPct: 10 },
    { slot: "dinner", days: 10, pricePerDay: 219, totalPrice: 2190 },
    { slot: "dinner", days: 20, pricePerDay: 208, totalPrice: 4160, popular: true, discountPct: 5 },
    { slot: "dinner", days: 30, pricePerDay: 197, totalPrice: 5910, discountPct: 10 },
    { slot: "both", days: 10, pricePerDay: 347, totalPrice: 3470, comboSaving: 610 },
    { slot: "both", days: 20, pricePerDay: 330, totalPrice: 6600, popular: true, discountPct: 5, comboSaving: 1720 },
    { slot: "both", days: 30, pricePerDay: 312, totalPrice: 9360, discountPct: 10, comboSaving: 2640 },
  ],
  r2: [
    { slot: "lunch", days: 10, pricePerDay: 169, totalPrice: 1690 },
    { slot: "lunch", days: 20, pricePerDay: 161, totalPrice: 3220, popular: true, discountPct: 5 },
    { slot: "lunch", days: 30, pricePerDay: 152, totalPrice: 4560, discountPct: 10 },
  ],
  r3: [
    { slot: "lunch", days: 10, pricePerDay: 199, totalPrice: 1990 },
    { slot: "lunch", days: 20, pricePerDay: 189, totalPrice: 3780, popular: true, discountPct: 5 },
    { slot: "lunch", days: 30, pricePerDay: 179, totalPrice: 5370, discountPct: 10 },
    { slot: "dinner", days: 10, pricePerDay: 229, totalPrice: 2290 },
    { slot: "dinner", days: 20, pricePerDay: 218, totalPrice: 4360, popular: true, discountPct: 5 },
    { slot: "dinner", days: 30, pricePerDay: 206, totalPrice: 6180, discountPct: 10 },
    { slot: "both", days: 10, pricePerDay: 364, totalPrice: 3640, comboSaving: 640 },
    { slot: "both", days: 20, pricePerDay: 345, totalPrice: 6900, popular: true, discountPct: 5, comboSaving: 1820 },
    { slot: "both", days: 30, pricePerDay: 327, totalPrice: 9810, discountPct: 10, comboSaving: 2730 },
  ],
  r4: [
    { slot: "lunch", days: 10, pricePerDay: 229, totalPrice: 2290 },
    { slot: "lunch", days: 20, pricePerDay: 218, totalPrice: 4360, popular: true, discountPct: 5 },
    { slot: "lunch", days: 30, pricePerDay: 206, totalPrice: 6180, discountPct: 10 },
    { slot: "dinner", days: 10, pricePerDay: 249, totalPrice: 2490 },
    { slot: "dinner", days: 20, pricePerDay: 237, totalPrice: 4740, popular: true, discountPct: 5 },
    { slot: "dinner", days: 30, pricePerDay: 224, totalPrice: 6720, discountPct: 10 },
    { slot: "both", days: 10, pricePerDay: 406, totalPrice: 4060, comboSaving: 720 },
    { slot: "both", days: 20, pricePerDay: 386, totalPrice: 7720, popular: true, discountPct: 5, comboSaving: 2080 },
    { slot: "both", days: 30, pricePerDay: 365, totalPrice: 10950, discountPct: 10, comboSaving: 2970 },
  ],
  r5: [
    { slot: "lunch", days: 10, pricePerDay: 169, totalPrice: 1690 },
    { slot: "lunch", days: 20, pricePerDay: 161, totalPrice: 3220, popular: true, discountPct: 5 },
    { slot: "lunch", days: 30, pricePerDay: 152, totalPrice: 4560, discountPct: 10 },
    { slot: "dinner", days: 10, pricePerDay: 199, totalPrice: 1990 },
    { slot: "dinner", days: 20, pricePerDay: 189, totalPrice: 3780, popular: true, discountPct: 5 },
    { slot: "dinner", days: 30, pricePerDay: 179, totalPrice: 5370, discountPct: 10 },
    { slot: "both", days: 10, pricePerDay: 313, totalPrice: 3130, comboSaving: 550 },
    { slot: "both", days: 20, pricePerDay: 297, totalPrice: 5940, popular: true, discountPct: 5, comboSaving: 1560 },
    { slot: "both", days: 30, pricePerDay: 282, totalPrice: 8460, discountPct: 10, comboSaving: 2340 },
  ],
};
